export { default as Navbar } from './Navbar'
export { default as Homepage } from './Homepage'
export { default as Exchanges } from './Exchanges'
export { default as Cryptos } from './Cryptos'
export { default as CryptoDetails } from './CryptoDetails'
export { default as News } from './News'
